### ISSUE TITLE
Toolbar button state for Action List not changed when closing window from window button

### ISSUE THREAD

**Issue by slubman** [Alshain01/ActionGroupManager#2]
When closing the Action List window, using the window close button, the toolbar button state is not reset.

Steps to show the wrong behavior:

1. Click the toolbar Action Group List button
1. Click the close button in the Action Group List window
1. Look at the toolbar Action Group List button still displaying the red arrow (window supposed to be active ?)

When closing the window by pressing the toolbar Action Group List button, the state revert to the white arrow.

**Comment by Alshain01** [comment]
Fixed in next release

[Commit](https://github.com/Alshain01/ActionGroupManager/commit/f3a2957eb49a720717c2580609f85e7847f68e92)
