### ISSUE TITLE
KSP 1.3.1 crash

### ISSUE THREAD

**Issue by LouisCyfer** [Alshain01/ActionGroupManager#5]
I know it should be working according to your [ActionGroupManager.version](https://github.com/Alshain01/ActionGroupManager/blob/master/ActionGroupManager/ActionGroupManager.version) but v2.2 crashes KSP 1.3.1

KSP.log doesnt show up anything but when I uninstall AGM KSP loads up perfectly :/

Would be amazing if you update and/or recompile or fix that issue.

**Comment by Real-Gecko** [comment]
Recompiling `AGM-LiteUI.dll` and `ActionGroupManager.dll` does not solve the problem.
Crash caused by `AGM-VisualUI.dll`, only after recompiling it game starts flawlessly.

**Comment by Alshain01** [comment]
Fixed in 2.2.1
